import { type ReactNode } from 'react'
import { Sparkles, ShieldCheck, Zap, Activity, Cpu, Globe, Target, Layers } from 'lucide-react'
import { cn } from '@/lib/utils'

export default function AuthLayout({ children }: { children: ReactNode }) {
    return (
        <div className="min-h-screen flex bg-black overflow-hidden relative font-sans">
            {/* Cinematic Background */}
            <div className="ambient-bg" />
            
            <div className="absolute inset-0 pointer-events-none overflow-hidden">
                <div className="absolute -top-[10%] -left-[10%] w-[40%] h-[40%] rounded-full bg-sidebar-primary/10 blur-[120px] opacity-20 animate-pulse" />
                <div className="absolute top-[20%] right-[5%] w-[30%] h-[30%] rounded-full bg-sidebar-primary/5 blur-[100px] opacity-20" />
            </div>

            {/* Left panel - Branding (Digital Asset Vibe) */}
            <div className="hidden lg:flex lg:w-7/12 flex-col justify-between pt-16 px-24 pb-20 relative z-10 border-r border-white/5">
                <div className="relative">
                    {/* Logo Premium */}
                    <div className="flex items-center gap-6">
                        <img src="/logo.png" alt="InvestMais Finance" className="h-20 w-auto object-contain filter brightness-200" />
                    </div>
                </div>

                <div className="max-w-3xl space-y-20">
                    {/* Headline Matriz */}
                    <div className="space-y-8">
                        <div className="flex items-center gap-4">
                            <div className="w-1.5 h-1.5 rounded-full bg-sidebar-primary netlife-glow" />
                            <span className="text-[10px] font-black text-sidebar-primary uppercase tracking-[0.5em] italic">Executive Intelligence Hub</span>
                        </div>
                        <h1 className="text-8xl font-black text-white leading-[0.95] tracking-tighter uppercase italic">
                            Empower Your <br />
                            <span className="text-transparent bg-clip-text bg-gradient-to-r from-sidebar-primary to-blue-400">
                                Global Reach.
                            </span>
                        </h1>
                        <p className="text-white/20 text-xl leading-relaxed font-black uppercase tracking-widest max-w-xl italic">
                            Elevate your financial performance with high-fidelity digital assets generated by neural architecture.
                        </p>
                    </div>

                    {/* Feature Cards Grid */}
                    <div className="grid grid-cols-2 gap-8">
                        {[
                            {
                                title: 'Neural Scaling',
                                desc: 'High-velocity script & video generation at scale.',
                                icon: Zap,
                                color: 'text-sidebar-primary'
                            },
                            {
                                title: 'Compliance Matrix',
                                desc: 'CVM protocols and institutional terms verified.',
                                icon: ShieldCheck,
                                color: 'text-emerald-400'
                            }
                        ].map((item, i) => (
                            <div key={i} className="nl-glass border-white/5 p-10 rounded-[40px] group hover:border-sidebar-primary/40 transition-all duration-700 relative overflow-hidden">
                                <div className="absolute inset-0 bg-gradient-to-br from-white/[0.02] to-transparent opacity-0 group-hover:opacity-100 transition-opacity" />
                                <div className="w-12 h-12 rounded-2xl bg-white/[0.03] flex items-center justify-center mb-8 border border-white/5 group-hover:border-sidebar-primary/20 group-hover:bg-sidebar-primary/5 transition-all">
                                    <item.icon className={cn("w-6 h-6", item.color)} />
                                </div>
                                <h4 className="text-white font-black text-sm uppercase tracking-widest italic">{item.title}</h4>
                                <p className="text-white/10 text-[9px] mt-4 font-black uppercase leading-relaxed tracking-[0.2em]">{item.desc}</p>
                            </div>
                        ))}
                    </div>

                    {/* Confidence Indicator */}
                    <div className="flex items-center gap-10 pt-10 border-t border-white/5">
                        <div className="flex -space-x-6">
                            {[1, 2, 3, 4].map((i) => (
                                <div key={i} className="w-16 h-16 rounded-[24px] border-4 border-black bg-white/[0.02] flex items-center justify-center text-[11px] text-sidebar-primary font-black uppercase tracking-widest backdrop-blur-3xl border-white/5 shadow-2xl">
                                    NODE
                                </div>
                            ))}
                        </div>
                        <div className="space-y-1.5">
                            <span className="text-white font-black text-sm uppercase tracking-widest italic">500+ Financial Experts Active</span>
                            <p className="text-[10px] text-white/10 font-black uppercase tracking-[0.3em] italic">Real-time system synchronization active</p>
                        </div>
                    </div>
                </div>

                <div className="text-white/10 text-[9px] font-black tracking-[0.5em] uppercase pt-10 flex items-center gap-6">
                    <span>© 2024 InvestMais Executive Hub</span>
                    <span className="w-1 h-1 rounded-full bg-white/10" />
                    <span className="italic">All Protocols Reserved</span>
                </div>
            </div>

            {/* Right panel - Auth form (Glass Container) */}
            <div className="flex-1 flex items-center justify-center p-8 lg:p-24 relative z-10">
                <div className="w-full max-w-xl">
                    {/* Mobile logo */}
                    <div className="lg:hidden flex flex-col items-center gap-6 mb-16">
                        <img src="/logo.png" alt="InvestMais Finance" className="h-16 w-auto object-contain filter brightness-200" />
                    </div>

                    <div className="nl-glass p-16 rounded-[64px] border-white/5 shadow-[0_80px_150px_rgba(0,0,0,0.8)] relative overflow-hidden group">
                        <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,hsl(var(--primary)/0.03)_0%,transparent_60%)]" />
                        
                        {/* Status bar top */}
                        <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-sidebar-primary to-transparent opacity-40" />
                        
                        {children}
                    </div>
                    
                    <div className="mt-12 text-center">
                        <p className="text-[9px] font-black text-white/5 uppercase tracking-[0.8em]">Neural Core Access System // v4.0.0</p>
                    </div>
                </div>
            </div>
        </div>
    )
}
