import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1440px" },
    },
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      fontSize: {
        'h1':    ['2rem',     { lineHeight: '1.2', fontWeight: '700' }],
        'h2':    ['1.5rem',   { lineHeight: '1.3', fontWeight: '600' }],
        'h3':    ['1.25rem',  { lineHeight: '1.4', fontWeight: '600' }],
        'body':  ['1rem',     { lineHeight: '1.6' }],
        'small': ['0.875rem', { lineHeight: '1.5' }],
        'xs':    ['0.75rem',  { lineHeight: '1.4' }],
      },
      colors: {
        border: "hsl(var(--border))",
        input:  "hsl(var(--input))",
        ring:   "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary:     { DEFAULT: "hsl(var(--primary))",     foreground: "hsl(var(--primary-foreground))" },
        secondary:   { DEFAULT: "hsl(var(--secondary))",   foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted:       { DEFAULT: "hsl(var(--muted))",       foreground: "hsl(var(--muted-foreground))" },
        accent:      { DEFAULT: "hsl(var(--accent))",      foreground: "hsl(var(--accent-foreground))" },
        popover:     { DEFAULT: "hsl(var(--popover))",     foreground: "hsl(var(--popover-foreground))" },
        card:        { DEFAULT: "hsl(var(--card))",        foreground: "hsl(var(--card-foreground))" },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        success: { DEFAULT: "hsl(var(--success))", foreground: "hsl(var(--success-foreground))" },
        warning: { DEFAULT: "hsl(var(--warning))", foreground: "hsl(var(--warning-foreground))" },
        info:    { DEFAULT: "hsl(var(--info))",    foreground: "hsl(var(--info-foreground))" },
        gray: {
          50: "hsl(var(--gray-50))", 100: "hsl(var(--gray-100))", 200: "hsl(var(--gray-200))",
          400: "hsl(var(--gray-400))", 500: "hsl(var(--gray-500))", 600: "hsl(var(--gray-600))",
          900: "hsl(var(--gray-900))",
        },
        chart: {
          "1": "hsl(var(--chart-1))", "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))", "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl:  "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      boxShadow: {
        'card':            '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
        'card-hover':      '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
        'elevated':        '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
        'subtle':          '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        'cinematic':       '0 25px 50px -12px rgb(0 0 0 / 0.8), 0 0 0 1px hsl(215 100% 50% / 0.05)',
        'card-lift':       '0 20px 40px -10px rgb(0 0 0 / 0.6), 0 0 0 1px hsl(195 100% 60% / 0.1)',
        'glow':            '0 0 40px hsl(215 100% 50% / 0.35), 0 0 80px hsl(195 100% 60% / 0.15)',
        'glow-soft':       '0 0 24px hsl(215 100% 50% / 0.2)',
        'glow-intense':    '0 0 60px hsl(195 100% 60% / 0.5), 0 0 120px hsl(215 100% 50% / 0.25)',
        'btn-primary-hover': '0 0 24px hsl(215 100% 50% / 0.4)',
      },
      spacing: { '18': '4.5rem', '22': '5.5rem' },
      maxWidth: { 'container': '1440px' },
      transitionDuration: { '150': '150ms', '200': '200ms', '300': '300ms', '500': '500ms', '700': '700ms' },
      transitionTimingFunction: {
        'cinematic': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'snap':      'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      keyframes: {
        "accordion-down":    { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up":      { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "slide-in-right":    { from: { transform: "translateX(100%)" }, to: { transform: "translateX(0)" } },
        "slide-out-right":   { from: { transform: "translateX(0)" }, to: { transform: "translateX(100%)" } },
        "fade-in":           { from: { opacity: "0", transform: "translateY(8px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "fade-out":          { from: { opacity: "1" }, to: { opacity: "0" } },
        "scale-in":          { from: { transform: "scale(0.95)", opacity: "0" }, to: { transform: "scale(1)", opacity: "1" } },
        "ripple":            { "0%": { transform: "scale(0)", opacity: "0.5" }, "100%": { transform: "scale(4)", opacity: "0" } },
        "slide-up":          { from: { opacity: "0", transform: "translateY(40px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "slide-down":        { from: { opacity: "0", transform: "translateY(-40px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "float":             { "0%, 100%": { transform: "translateY(0) translateX(0)" }, "50%": { transform: "translateY(-12px) translateX(6px)" } },
        "pulse-glow":        { "0%, 100%": { boxShadow: "0 0 20px hsl(215 100% 50% / 0.3), 0 0 40px hsl(195 100% 60% / 0.15)" }, "50%": { boxShadow: "0 0 40px hsl(215 100% 50% / 0.6), 0 0 80px hsl(195 100% 60% / 0.3)" } },
        "cinematic-zoom":    { from: { opacity: "0", transform: "scale(1.15)", filter: "blur(8px)" }, to: { opacity: "1", transform: "scale(1)", filter: "blur(0)" } },
        "ken-burns":         { from: { transform: "scale(1) translate(0, 0)" }, to: { transform: "scale(1.08) translate(-2%, -1%)" } },
      },
      animation: {
        "accordion-down":  "accordion-down 0.2s ease-out",
        "accordion-up":    "accordion-up 0.2s ease-out",
        "slide-in-right":  "slide-in-right 0.3s ease-out",
        "slide-out-right": "slide-out-right 0.3s ease-out",
        "fade-in":         "fade-in 0.4s cubic-bezier(0.16, 1, 0.3, 1) both",
        "fade-out":        "fade-out 0.2s ease-out",
        "scale-in":        "scale-in 0.3s cubic-bezier(0.16, 1, 0.3, 1) both",
        "ripple":          "ripple 0.6s linear",
        "slide-up":        "slide-up 0.6s cubic-bezier(0.16, 1, 0.3, 1) both",
        "slide-down":      "slide-down 0.6s cubic-bezier(0.16, 1, 0.3, 1) both",
        "float":           "float 6s ease-in-out infinite",
        "pulse-glow":      "pulse-glow 2.5s ease-in-out infinite",
        "cinematic-zoom":  "cinematic-zoom 1.2s cubic-bezier(0.16, 1, 0.3, 1) both",
        "ken-burns":       "ken-burns 20s ease-in-out infinite alternate",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
