import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1440px" },
    },
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      fontSize: {
        'h1':    ['2rem',     { lineHeight: '1.2', fontWeight: '700' }],
        'h2':    ['1.5rem',   { lineHeight: '1.3', fontWeight: '600' }],
        'h3':    ['1.25rem',  { lineHeight: '1.4', fontWeight: '600' }],
        'body':  ['1rem',     { lineHeight: '1.6' }],
        'small': ['0.875rem', { lineHeight: '1.5' }],
        'xs':    ['0.75rem',  { lineHeight: '1.4' }],
      },
      colors: {
        border: "hsl(var(--border))",
        input:  "hsl(var(--input))",
        ring:   "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary:     { DEFAULT: "hsl(var(--primary))",     foreground: "hsl(var(--primary-foreground))" },
        secondary:   { DEFAULT: "hsl(var(--secondary))",   foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted:       { DEFAULT: "hsl(var(--muted))",       foreground: "hsl(var(--muted-foreground))" },
        accent:      { DEFAULT: "hsl(var(--accent))",      foreground: "hsl(var(--accent-foreground))" },
        popover:     { DEFAULT: "hsl(var(--popover))",     foreground: "hsl(var(--popover-foreground))" },
        card:        { DEFAULT: "hsl(var(--card))",        foreground: "hsl(var(--card-foreground))" },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        success: { DEFAULT: "hsl(var(--success))", foreground: "hsl(var(--success-foreground))" },
        warning: { DEFAULT: "hsl(var(--warning))", foreground: "hsl(var(--warning-foreground))" },
        info:    { DEFAULT: "hsl(var(--info))",    foreground: "hsl(var(--info-foreground))" },
        gray: {
          50: "hsl(var(--gray-50))", 100: "hsl(var(--gray-100))", 200: "hsl(var(--gray-200))",
          400: "hsl(var(--gray-400))", 500: "hsl(var(--gray-500))", 600: "hsl(var(--gray-600))",
          900: "hsl(var(--gray-900))",
        },
        chart: {
          "1": "hsl(var(--chart-1))", "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))", "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl:  "0.75rem",
        "2xl": "1rem",
      },
      boxShadow: {
        'card':       '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
        'card-hover': '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
        'elevated':   '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
        'subtle':     '0 1px 2px 0 rgb(0 0 0 / 0.05)',
      },
      spacing: { '18': '4.5rem', '22': '5.5rem' },
      maxWidth: { 'container': '1440px' },
      transitionDuration: { '150': '150ms', '200': '200ms', '300': '300ms' },
      keyframes: {
        "accordion-down":    { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up":      { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "slide-in-right":    { from: { transform: "translateX(100%)" }, to: { transform: "translateX(0)" } },
        "slide-out-right":   { from: { transform: "translateX(0)" }, to: { transform: "translateX(100%)" } },
        "fade-in":           { from: { opacity: "0", transform: "translateY(4px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "fade-out":          { from: { opacity: "1" }, to: { opacity: "0" } },
        "scale-in":          { from: { transform: "scale(0.98)", opacity: "0" }, to: { transform: "scale(1)", opacity: "1" } },
        "ripple":            { "0%": { transform: "scale(0)", opacity: "0.5" }, "100%": { transform: "scale(4)", opacity: "0" } },
      },
      animation: {
        "accordion-down":  "accordion-down 0.2s ease-out",
        "accordion-up":    "accordion-up 0.2s ease-out",
        "slide-in-right":  "slide-in-right 0.3s ease-out",
        "slide-out-right": "slide-out-right 0.3s ease-out",
        "fade-in":         "fade-in 0.2s ease-out",
        "fade-out":        "fade-out 0.2s ease-out",
        "scale-in":        "scale-in 0.2s ease-out",
        "ripple":          "ripple 0.6s linear",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
